---
title: "An Introduction to excerptr"
author: "Andreas Dominik Cullmann"
date: 2017-05-01, 21:59:20
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{An Introduction to excerptr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
excerptr is an R interface to the python package [excerpts](https://pypi.python.org/pypi/excerpts).
See there for more on the Why.

Suppose you have a script

```{r, comment = ""}
path <- system.file("tests", "files", "some_file.R", package = "excerptr")
cat(readLines(path), sep = "\n")
```
and you would want to excerpt the comments marked by '%' into a file giving you the table of contents of your script.
Then 
```{r}
excerptr::excerptr(file_name = path, run_pandoc = FALSE, output_path = tempdir())
```
gives you

```{r, comment = ""}
cat(readLines(file.path(tempdir(), sub("\\.R$", ".md", basename(path)))), 
    sep = "\n")
```

If you have pandoc installed, you can convert the markdown output into html:

```{r}
if (length(Sys.which("pandoc") >= 0))
    excerptr::excerptr(file_name = path, pandoc_formats= "html", 
                       output_path = tempdir())
```
This gives you
```{r, comment = ""}
if (length(Sys.which("pandoc") >= 0))
    cat(readLines(file.path(tempdir(), sub("\\.R$", ".html", basename(path)))), 
        sep = "\n")
```
```{r, echo = FALSE, results = "hide"}
if (length(Sys.which("pandoc") >= 0))
    excerptr::excerptr(file_name = path, pandoc_formats= "html", 
                       output_path = file.path(rprojroot::find_root(rprojroot::is_r_package), 
                                               "inst", "tests", "files")
                       )
```
You can see this html file [here](http://htmlpreview.github.io/?https://github.com/fvafrCU/excerptr/blob/master/inst/tests/files/some_file.html).
